<html>
    
    <head>
        <meta http-equiv = "Content-Type" content = "text/html; charset=utf-8" />
		<meta http-equiv = "X-UA-Compatible" content = "IE=edge">
		<title>Clicker Raid Multiplayer</title>
        
                <!-- Template js -->
        <script src="js/jquery-2.1.1.min.js"></script>
        <script src="js/jquery.appear.js"></script>
        <script src="js/contact_me.js"></script>
        <script src="js/jqBootstrapValidation.js"></script>
        <script src="js/modernizr.custom.js"></script>
        <script src="js/script.js"></script>
        <script src="bootstrap/js/bootstrap.min.js"></script>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        
  		<!--<embed src="sounds/hit.mp3" autoplayt=false width=0 height=0 name="hit" enablejavascript="true" type="audio/mpeg">-->
  		 

        <!-- Font Awesome CSS -->
        <link href="css/font-awesome.min.css" rel="stylesheet">
		
		<!-- Custom CSS -->
        <link href="css/animate.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="css/style.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
        
        <link href="css/frame.css" rel="stylesheet">
        
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/png" href="favicon.png" />
        
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
        
        <script src = "include/cr.js"></script>
  		
  	</head>